version: '3'

# docker network create nginx_bridge
networks:
  nginx_bridge:
    driver: bridge

services:
  nginx:
    image: guid_web:1.0
    container_name: my_guid_web
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai 
    ports:
      - 80:80
    volumes:
      #- ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    networks:
      - nginx_bridge